### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by a2batic**
Tendrl-bug-id:  #822, #829, #768, #833

### CODE REVIEW

**Review by gnehapk — DISMISSED** [review]

**Comment by a2batic** [comment]
@Tendrl/admins @cloudbehl please review.

**Review by cloudbehl — DISMISSED** [review]

**Comment by cybernth** [comment]
@a2batic, can you rebase the patch

**Comment by a2batic** [comment]
@nthomas-redhat done

**Review by cybernth — APPROVED** [review]
LGTM

**Review by gnehapk — APPROVED** [review]

**Pull request merged**
