### PR TITLE
Small Bugs fix

### PR DESCRIPTION
**Pull request by a2batic**
Tendrl-bug-id: #747 #752 #753 #754

### CODE REVIEW

**Comment by r0h4n** [comment]
If these are look and feel bugs only, please review them by today. We need to cut a build

**Comment by gnehapk** [comment]
@r0h4n @a2batic is working on review comments.  IMO, we should not merge this PR right now for 3.3 release.

**Comment by r0h4n** [comment]
@gnehapk @cloudbehl @a2batic Is this done?

**Comment by cloudbehl** [comment]
the code looks good to me

**Pull request merged**
