### PR TITLE
Packaging: Rename tendrl-dashboard into tendrl-ui

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@r0h4n , @nthomas-redhat , @gnehapk, @rishubhjain , Please review

**Comment by TimothyAsirJeyasing** [comment]
@cloudbehl Please review

**Comment by gnehapk** [comment]
LGTM

**Comment by TimothyAsirJeyasing** [comment]
This patch is required for jenkins ci. Will it be ok to keep the file name as tendrl-dasboard.spec or we need to change the spec file name also.

**Review by r0h4n — APPROVED** [review]

**Comment by r0h4n** [comment]
@mbukatov Please note changes in rpm name from tendrl-dashboard to tendrl-ui

**Pull request merged**
