### PR TITLE
Implements Concept B: Single Cluster / Element Manager Concept with Context Switcher Navigation (Optimized UX)

### PR DESCRIPTION
**Pull request by bleathem**
This PR implements _Concept B: Single Cluster / Element Manager Concept with Context Switcher Navigation (Optimized UX)_

Included in this PR are a number of changes:
- The alerts.json and notifications.json test data are updated to reflect current values
- An optional _server.js_ file is introduced that uses browser-sync to improve the local development experience
- A .editorconfig file is introduced to align local code editor config with the style used in the project.

I will record and include a video demonstrating the changes as a comment to this PR.

### CODE REVIEW

**Comment by bleathem** [comment]
A video of the features implemented with this PR:
https://bluejeans.com/s/WS76C/

**Comment by r0h4n** [comment]
@bleathem New features need to land on feature branches, I have created one for your (https://github.com/Tendrl/ui/tree/spec/alternate_concept_b), please send this PR on that branch ("spec/alternate_concept_b")

**Comment by bleathem** [comment]
@r0h4n FYI: PRs can re updated to target new branches without closing them:
https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by r0h4n** [comment]
@bleathem Ohh, thats pretty neat, please change the base branch on this PR then.

**Comment by cloudbehl** [comment]
@bleathem Thanks for your Contribution. Below we have mentioned few points which we will like to highlight and discuss with you, @julienlim and @mcarrano. 

1. Select the cluster from the drop-down, click on stack button(Navigation Close/Open button) 1 time only and then change to all clusters. The left navigation is getting present in case of  "all cluster" selection.

screenshot from 2017-10-24 11-53-13

2. Login screen shows the left navigation placeholder.

screenshot from 2017-10-24 11-33-05

3. When the "Settings>Users" is selected, there is no way to go back to "all-cluster" until you click the logo.(U/X Design)

4. Task List page is Missing.
screenshot from 2017-10-24 15-56-29

5. Cluster List - Do we still need details button in front of every cluster. As context switcher fulfills all the functionality.(U/X design)

Need a Discussion with @bleathem regarding the "server.js" file.
 - What other purpose does server.js resolve except for browser sync? Can we include this in gulpfile.js?

**Comment by julienlim** [comment]
@cloudbehl @bleathem @mcarrano 

In response to @cloudbehl's questions:

1. Left-nav should not be present when “All Clusters” selected.
screen shot 2017-10-24 at 4 19 20 pm

2. Login screen should not show left nav — looks like be a bug.

3. When Settings -> Users selected, context switcher switches to “All Clusters” (so you’re already there).  To switch to another cluster, you would use the context-switcher to switch to another cluster.
screen shot 2017-10-24 at 4 21 11 pm

4. +1 Tasks is missing from the Menu, it should be the last item in the Navigation menu on the left.

5. Once context switcher fulfills all its functionality, you’re correct that we won’t need details in front of every cluster.

Note: Screenshots are from the recording that @bleathem provided (https://bluejeans.com/s/WS76C/).

**Comment by bleathem** [comment]
I'll take a look at the bugs with showing/hiding the navigation menu and post an update to this PR.

As for the browser sync script, I initially implemented it via the gulp file, but the "clean" task run when the gulp file is loaded made it problematic.  A proper treatment would involve using the gulp [run-sequence](https://www.npmjs.com/package/run-sequence) plugin to ensure the clean task gets executed in the right order.  I felt that was out of scope for this PR but I'm happy to introduce it via another PR if the team is interested.  We should probably just drop the server.js script from this PR.

**Comment by julienlim** [comment]
@cloudbehl Please see @bleathem's reply above.

**Comment by bleathem** [comment]
I added a commit to this PR that removed the ambiguity between using angular and the jQuery plugin to manage navigation state.  A more rigorous (but time consuming) solution would be to adopt the angular-patternfly [vertical navigation component](http://www.patternfly.org/angular-patternfly/#/api/patternfly.navigation.component:pfVerticalNavigation%20-%20Basic).

This commit resolves the vertical navigation bugs described above, while not interfering with the responsive capabilities of the plugin.

Note for 3): when "Settings>Users" was selected, the context switcher erroneously reported "All Clusters" as being selected.  This meant one could not select "All Clusters" to get back to the cluster list, and had to instead click the logo.  I took the liberty of adding a disabled "Select a cluster..." option to allow for a use case where neither all clusters, nor a single cluster is selected in the context switcher.

**Comment by cloudbehl** [comment]
For the run Sequence I think we can have the script for now, Later will add it gulp file by adding proper sequence.

>  when "Settings>Users" was selected, the context switcher erroneously reported "All Clusters" as being selected. This meant one could not select "All Clusters" to get back to the cluster list, and had to instead click the logo. I took the liberty of adding a disabled "Select a cluster..." option to allow for a use case where neither all clusters, nor a single cluster is selected in the context switcher.

Yes Agreed its a good solution to have a "Select a cluster" in a dropdown.


Last thing left is to add "Task List" on the navigation.If you got time to resolve this issue its good otherwise I can add it.

**Comment by julienlim** [comment]
@cloudbehl I think you may have to add "Task List" as not sure @bleathem will have time to get to it.  Thank you.

**Comment by gnehapk** [comment]
@bleathem When I ran `npm install` command, below error is coming -
```
[neha@dhcp35-170 tendrl_frontend]$ npm install
npm ERR! Linux 4.8.13-100.fc23.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: angular-patternfly@~3.26.1
npm ERR! notarget Valid install targets:
npm ERR! notarget 4.12.0, 4.11.8, 4.11.7, 4.11.6, 4.11.5, 4.11.4, 4.11.3, 4.11.2, 4.11.1, 4.11.0, 4.10.0, 4.9.1, 4.9.0, 4.8.2, 4.8.1, 4.8.0, 4.7.3, 4.7.2, 4.7.1, 4.7.0, 4.6.0, 4.5.6, 4.5.5, 4.5.4, 4.5.3, 4.5.2, 4.5.1, 4.5.0, 4.4.1, 4.4.0, 4.3.8, 4.3.7, 4.3.6, 4.3.5, 4.3.4, 4.3.3, 4.3.2, 4.3.1, 4.3.0, 4.2.0, 4.1.1, 4.1.0, 4.0.0, 4.0.0-rc.1, 4.0.0-alpha.3, 4.0.0-alpha.2, 4.0.0-alpha.1, 3.25.0, 3.24.0, 3.23.3, 3.23.2, 3.23.1, 3.23.0, 3.22.1, 3.21.0, 3.20.0, 3.19.0, 3.18.1, 3.18.0, 3.17.0, 3.16.0, 3.15.0, 3.14.0, 3.13.0, 3.12.0, 3.11.0, 3.10.0, 3.9.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'Tendrl'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
```

Since there is no package present for angular-patternfly of version "~3.26.1" (mentioned in the package.json file), this error is coming. So, I tried with "~4.0.0" version, still login screen shows the left navigation placeholder and in the console, I can see error- "TypeError: Cannot read property 'showMenu' of undefined".

login-screen

**Comment by bleathem** [comment]
@gnehapk sorry, I accidenally bumped the angular-patternfly version instead of the patternfly one.  I've added a new commit addressing the issue.  The error you were seeing was as a result of being on the older patternfly that doesn't expose the vertical navigation API.

@cloudbehl I've updated the PR with an additional commit putting back the Tasks menu item.

**Comment by r0h4n** [comment]
@gnehapk  @a2batic  @cloudbehl  Please update your reviews in detail.

Some updates from today's upstream call:
- There's an API change required for accommodating per cluster alerts/tasks etc.
- This PR has been tested with the required Pattern-fly version and there are some errors which are being looked at due to the change of version

**Comment by a2batic** [comment]
@julienlim @r0h4n @nthomas-redhat 
Current code + patternfly@3.29.13 + concept B PR = Not breaking anything.
We need time to integrate APIs and implement corresponding task and event views.
Also, the patternfly upgrade notes can be seen here : #704

**Comment by julienlim** [comment]
@r0h4n @nthomas-redhat @a2batic Thanks for commenting on where this PR stands.  Noted that Current code + patternfly@3.29.13 + concept B PR = Not breaking anything.

Regarding the Task, Event, (and Alerts)) views, irrespective of the navigation, these do need to be addressed/fixed.

**Comment by gnehapk** [comment]
@julienlim @mcarrano 

1) Does the context selector also list the unmanaged clusters along with the managed one? If so, then how the user will differentiate between the unmanaged one? IMO, we can disable the unmanaged cluster option from the dropdown. 
disabled-unmanaged-cluster


2)Since, we don't show the details for unmanaged cluster, where the task for "Import Cluster" will be listed? As per the Concept B design, the tasks are displayed per cluster and the task list along with the other context specific details are only available for managed cluster[1].

1. https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/251481034

**Comment by mcarrano** [comment]
@gnehapk Yes, I agree that it does not make sense to list unmanaged clusters in the context selector. These would only be shown in the All Clusters view.

Good question about accessing Import task progress for new clusters. Is it possible to enable examining details for a cluster once an import operation has been initiated? This would allow the user to access the task list for that cluster. Obviously all detail screens can not be populated or available until the cluster import is complete. Alternatively, we can add a link to the All Clusters view to open the import task details in a modal as we do for import errors. Thoughts?

**Comment by gnehapk** [comment]
Closing this PR as another [PR](https://github.com/Tendrl/ui/pull/776) has been sent for it after rebasing with the latest master code.

**Pull request closed without merging**
