### PR TITLE
[WIP] Enabled expand action if expand fails

### PR DESCRIPTION
**Pull request by gnehapk**
Bugzilla: 1596655
tendrl-bug-id: https://github.com/Tendrl/ui/issues/1025

Signed-off-by: Neha Gupta <gnehapk@gmail.com>

### CODE REVIEW

**Review by cloudbehl — CHANGES_REQUESTED** [review]
This is not a good solution to this problem.
1. If the expansion is failed and the current job is something else your condition will disabled because if the expansion is failed cluster.state comes as empty string("") and  the job type will stay till any other job is triggered .

**Comment by gnehapk** [comment]
@cloudbehl If you have checked the condition properly its "AND" condition not "OR" so failed is checked against just ExpandClusterWithDetectedPeers job. It will not be compared with any other job.

Ideal way is to handle it via backend. @shtripat is going to create a RFE issue for it.

**Comment by cloudbehl** [comment]
This is your condition
(cluster.state === "expand_pending" || (cluster.jobType === "ExpandClusterWithDetectedPeers" && cluster.currentStatus === "failed"))

When job is failed and the job type is not ExpandClusterWithDetectedPeers then
cluster.state =  ""
job type = "ProfilingEnabled"
cluster.currentStatus = "finished"

So if you evaluate your query

("" === "expand_pending" || ("ProfilingEnabled" === "ExpandClusterWithDetectedPeers" && "finished" === "failed"))

(false || (false && false)) = false

Even the other cluster.currentStatus is failed for another job type

(false || (false && true)) = false

In both the above senario the condition should be passed so which eventually means there is no use of checking  ("ProfilingEnabled" === "ExpandClusterWithDetectedPeers" && "finished" === "failed") statement. We need to fallback to better solution that was my intention of saying that this is not a good solution.


>> Ideal way is to handle it via backend. @shtripat is going to create a RFE issue for it.

Yes I agree the state should be expand_pending even after the job is failed. 

The better and more full proof solution for now will be to check for nodes under the cluster list and if any node has is_managed false set to empty string("") then we should enable the expand cluster button.

**Comment by gnehapk** [comment]
@cloudbehl The above changes are done for allowing expand flow even if expand fails. So as per the current backend implementation, the cluster.state sets to "" even if cluster expansion fails which ideally should not be(it should be reset back to expand_pending on which @shtripat is working).  So `(cluster.jobType === "ExpandClusterWithDetectedPeers" `  is for checking this scenario. 

So for eg. if expansion fails,  the condtion

`(cluster.state === "expand_pending" || (cluster.jobType === "ExpandClusterWithDetectedPeers" && cluster.currentStatus === "failed"))`

will be
 
`("" === "expand_pending" || ("ExpandClusterWithDetectedPeers" === "ExpandClusterWithDetectedPeers" && "failed" === "failed"))` => ( false || (true && true)) => true 
and hence, `Expand` action will be shown on UI.

For other failed job for eg. ProfilingEnabled job, the condition will be -

`("" === "expand_pending" || ("ProfilingEnabled" === "ExpandClusterWithDetectedPeers" && "failed" === "failed"))` => (false || (false && true)) => false. Hence, expand action will be hidden.

So, the above condition fulfill all scenarios. Let me know if you need more clarity, we can discuss on bluejeans too.

**Comment by cloudbehl** [comment]
What if after the failure of expansion we run the Profiling disabled or enabled task the last job is not `cluster.jobType === "ExpandClusterWithDetectedPeers" ` . In that scenario, the expand should be enabled but as per the code implementation it will not be enabled.

`("" === "expand_pending" || ("ProfilingEnabled" === "ExpandClusterWithDetectedPeers" && "failed" === "failed"))`

`(false || (false && true))`

**Comment by gnehapk** [comment]
@cloudbehl Expand will be enabled if the state is set `expand_pending` or if the expansion fails. So if the last job is something else except  than ExpandClusterWithDetectedPeers and if the  state is not set set to expand_pending, expand should not be enabled and it as per the code it will not. 

i.e.e (false || (false && true)) => false

 And If the last job is something else except  than ExpandClusterWithDetectedPeers and if the  state is expand_pending(which means expansion is required) then it should enable the Expand link. And as per the code too it will enable. 

i.e. (true || (false  && true)) => true. 

Not sure what you are trying to say above.

**Comment by shtripat** [comment]
With https://github.com/Tendrl/gluster-integration/pull/685 in place we dont these changes in UI anymore

**Comment by gnehapk** [comment]
As per @shtripat above comment this PR is not needed any more. Hence, closing the PR.

**Pull request closed without merging**
