### PR TITLE
Modified grafana dashboard to relative path from static path

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
bugzilla: 1590416
tendrl-bug-id: Tendrl/ui#1073

Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@gnehapk @shirshendu @shtripat please review

**Review by gnehapk — APPROVED** [review]
LGTM

**Comment by gnehapk** [comment]
@GowthamShanmugam Please make sure that this PR should be merged only when the api changes are in.

**Comment by gnehapk** [comment]
@GowthamShanmugam are the API changes merged for this PR?

**Comment by GowthamShanmugam** [comment]
@gnehapk no, it is still under review

**Pull request merged**
